[package]
name = "physics-wasm"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
serde-wasm-bindgen = "0.4"
wasm-bindgen = "0.2.100"

[profile.release]
lto = true
